language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
sudo: false
cache:
  directories:
    - node_modules
notifications:
  email: false
env:
  - PLOTW_ADMINS="Shell"
  - PLOTW_CHANNELS="Shell"
  - PLOTW_SONG_LIMIT=1
